---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName grafana
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GF_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .GF_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # Grafana Database
        GF_DATABASE_HOST: postgres-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_NAME: *dbName
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres

        # OAuth
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"

        # Data Sources
        TESLAMATE_POSTGRES_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
        TESLAMATE_POSTGRES_PASS: "{{ .TESLAMATE_POSTGRES_PASS }}"
        GRAFANA_INFLUXDB_TOKEN: "{{ .GRAFANA_INFLUXDB_TOKEN }}"
        INFLUXDB_ORG_ID: "{{ .ORG_ID }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: influxdb
    - extract:
        key: teslamate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TESLAMATE_$1"
    - extract:
        key: cloudnative-pg
    - extract:
        key: authelia
