---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    type: prometheus
    name: Prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus-operated.observability.svc.cluster.local:9090
    isDefault: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    type: loki
    name: Loki
    uid: loki
    access: proxy
    url: http://loki-gateway.observability.svc.cluster.local
    jsonData:
      maxLines: 250
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    type: alertmanager
    name: Alertmanager
    uid: alertmanager
    access: proxy
    url: http://alertmanager-operated.observability.svc.cluster.local:9093
    jsonData:
      implementation: prometheus
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: influxdb
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  valuesFrom:
    - targetPath: datasource.secureJsonData.token
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: GRAFANA_INFLUXDB_TOKEN
    - targetPath: datasource.jsonData.organization
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: INFLUXDB_ORG_ID
  datasource:
    type: influxdb
    name: InfluxDB
    uid: influxdb
    access: proxy
    url: http://influxdb.observability.svc.cluster.local:8086
    jsonData:
      version: Flux
      defaultBucket: default
      tlsSkipVerify: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: teslamate
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  valuesFrom:
    - targetPath: datasource.user
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: TESLAMATE_POSTGRES_USER
    - targetPath: datasource.secureJsonData.password
      valueFrom:
        secretKeyRef:
          name: grafana-secret
          key: TESLAMATE_POSTGRES_PASS
  datasource:
    type: postgres
    name: TeslaMate
    access: proxy
    url: postgres-ro.database.svc.cluster.local:5432
    database: teslamate
    jsonData:
      postgresVersion: 1000
      sslmode: disable
