---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./grafanadashboard.yaml
  - ./grafanadatasource.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: grafana-dashboard-home-energy
    files:
      - home-energy.json=./dashboards/home-energy.json
generatorOptions:
  disableNameSuffixHash: true
