---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-dashboard
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - rook.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 7000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-rgw
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - rgw.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: rook-ceph-rgw-ceph-objectstore
          port: 80
