apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:b4+jbTux6OtFbSwKIQ9SXw==,iv:J7eTq/c2fKuCQ3mgvfBSrfvtrY5F24eMBXNkH3vHkM4=,tag:6fmt6z69SRDfzP6yCo1IFQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:rDh2EnXNPtkHcSNttU0=,iv:k1VPKlxwC498O2n7qkFyspn23SG62QwJKlIPB7OrfMY=,tag:P/cv4DdqEKFz0a9saGKuLQ==,type:str]
    SECRET_PUBLIC_ANON_DOMAIN: ENC[AES256_GCM,data:bbCLQ0z+t3tdXoRq,iv:+GmiYdm260xFptKxw8d8GDEZDWagKHBNmuOG3getbTI=,tag:vFql7qUksew3oFyw148amQ==,type:str]
    SECRET_PLEX_DOMAIN: ENC[AES256_GCM,data:rIwNpnfZguqdH4UH,iv:yGdKx5O/K/rVlWISMpENwbnjq1FaWj+U2u9XlGMDT9A=,tag:zZxb8PlUnZ6nGhZY7I0U4w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:a97SDTDH/TW9f1Pno3BsNbLeRt0=,iv:pB4ogbGxdcbb8XpORwJQzVC1ijhDSAlZV30oBBQfvHA=,tag:zXL0TX0LzgYzgGH2GRq0yg==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:RrGVXBSgzX7n1FEjLiIklTlxTHoiOUtSZnPEZoN6APQ=,iv:oZSHlzbXiE/fVVeVqlFc2IMej8JEc+ehC6EuQyM4qdQ=,tag:QnT4MfHow6C49TlzswDq5A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cmrIgug1qMj2jBlqA1iijgCbwSh48E7FzkIuelLQbPwJ/8NF,iv:otPMVM7yPvZmrLg3v0fCzDolCrLjIyFEZUy4uU2rndY=,tag:K8iD6oPSIy4a+BaLSdw38w==,type:str]
    SECRET_NFS_DOMAIN: ENC[AES256_GCM,data:4Fj+nN6etQoRu36JKnXzffY8Vyd7j2oEihD8,iv:nKI+aLwTtPw97sVFwbV5ZuZQfULhufTzdFq+NzYapCA=,tag:qWaYnXBnmv0FY+uNS69vUg==,type:str]
    SECRET_NFS_IP: ENC[AES256_GCM,data:clcHJFThL+T0,iv:64TQveQHmFeGKyjIkNISsjamaWz05vI9A1iO0pHQ1qo=,tag:+31u4rWDr9JfRMF3aunY6g==,type:str]
    TZ: ENC[AES256_GCM,data:WE0+y+BvfM1feLWrqXXkGA==,iv:sAiBEf2XlqPNE5irq7/vKCbiwRqezIq0+8W08z3sLJw=,tag:CnnZTl+3Ry/x7Mhfne7tqg==,type:str]
# noinspection KubernetesUnknownKeys
sops:
    age:
        - recipient: age1pvlc4c05yg9g0pst6f6uvthh7942vt5tx79ycva92y8matj2ne5qvz4md5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb0FKbWZva1BPZTNBZS93
            L09hNWU5TWFFWEV1NkkvZ2R6OS9Nanp4TGtZCkhCKy9FKytoSTE2UEFLaS84cDRw
            ZldyQXZFUDNsRHIzdFU1a204QmFhNmsKLS0tIG9yN01xWTBPc0Z6V2RPUnVPdC84
            Z1FvYjVhYnFnY3V0Y3NDbmpsaHZjOTgKAdPthVGTjniTw4pmiGPnHrbJ376UrxBj
            4BB9t5POvirLSsszEUTlZ44zKeOzSACmbqYqphyaO/Znpnb3Z5JKug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T10:49:40Z"
    mac: ENC[AES256_GCM,data:JyPl0nmheWSXW3LXnSZ6FRhfN9YxQGk7T0ZWy7iLFGSRJIJF8Y32JilNoXBGnGIVmKZQjFyaGf+euQnCpg1BbjU/rxtAw6JZTBq4hwvTzd32F75ojEE9ftuiG5RSx06dR6xOPgL7u1/Q4HJo+wjM4ZwQY9eLo/cjJvOwT2nO8xc=,iv:5w/uUnRq2IKWijcd/xpX4b+b1raIP5f3m0neocE80sw=,tag:PbPrjBzMB9hIxNXqo2ygew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
