apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Pctl5zzl8nfDxzAeIfFWyA==,iv:AqgPLjMf0GWhk0y3gA//6p0EJvIf8LFfkjcRn2PD0qM=,tag:87h6nv8NOsHQ7fq2q9ykdQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:E5NAosr1FWzSNIQ/ZJg=,iv:nsK0DjpCGZFcCQWjL0Sp4e/hIPnBoYd+45cXDgcC+1g=,tag:WIq1Sy1j+tZMne3IdyjiXA==,type:str]
    SECRET_PUBLIC_ANON_DOMAIN: ENC[AES256_GCM,data:Tj49UOnleHUPSns3,iv:NZqMemXtNvdPpCPLgUfgGLvRHP69e61+BaG70Y5y5CE=,tag:b7qX/BrW9PbjegnNwGUauA==,type:str]
    SECRET_PLEX_DOMAIN: ENC[AES256_GCM,data:DB7rvMmS8kEPZgK6,iv:KH/FyuGczve31FVRsH4mue0qFoRzwdB14FlKoSwFpVQ=,tag:2pk40p25AvsYnPYURaZotQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TTUe9FsoKRxWbfshA/Z4r4bjwmk=,iv:4gOPzU5nuqnCVhYEowUgsvnB2R3psbJkDyPDAZKf4ac=,tag:YQZl2OBEKOBHlKduzyxJpg==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:Htygc7jEG0/M7z2U69GO8NMMPS7UfeV0SaX/q/uNqnk=,iv:WQHkl1Xkt2w2rpdeYSPQTUlhaoY5cZfCH/QZo7mO4x8=,tag:nvDbrFbORW0qTQ2m9GjiUw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RCKSmncB41SwoAPyeKstGK57oMwbdwItEcyq0BjDni5pO9rj,iv:RO1oz2UvsDPDeVAnKjqkMZIIcthsD2JGMI7S3foGT74=,tag:gmQu5hvMqNjipM4Ceahrnw==,type:str]
    SECRET_NFS_DOMAIN: ENC[AES256_GCM,data:CZ9x8wPyDcd9mXX2WFOnygao2J0YmJiFv7S5,iv:MBXzvVkEkkPNryThT3nfOWDKcrftTXeypC9WfasHEMI=,tag:Xg9T1/bIVl922+RbSjHmWA==,type:str]
    SECRET_NFS_IP: ENC[AES256_GCM,data:NYlP6YfU1J0b,iv:q0+QyqWJtICrDAgmThEjff5e9d6ImUo4Za1R8Gl1N14=,tag:S5L/ZPzW5xNRPKZ67Yy3rQ==,type:str]
# noinspection KubernetesUnknownKeys
sops:
    age:
        - recipient: age1pvlc4c05yg9g0pst6f6uvthh7942vt5tx79ycva92y8matj2ne5qvz4md5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U1V2a0dWTm05MFE5UGtD
            bWQ2cTJrcHRUQzIrSVZNbEJqVWpSNHVOS3pBCm02RXVJNWxkamoxQThoMUwzOWFm
            cGZwVEI4aDVZLzFBTG9mNVpTcjVQaUkKLS0tIHJhQ3NRQnJJbUs5OU1nR2dQbkVN
            MW1NQi9GK2d6cWZ5OUpGM0pZRzFRa00KAynAXdo5ROzGnCDKNyWt5Z6YTOLSIdT2
            mq0PR1kbM482dfOSQAKi47QHppsPgebqDi2mt4eDby1B8bhwPnESUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T20:09:08Z"
    mac: ENC[AES256_GCM,data:zjOOXPW8QCl3CIUGDeB7B+Iqhmf3jJlRUJuNw+8f6iS0scc9jCbNmA1wO3tkipHToj0oaK46g+/J7oQoFBlBdo/YdehBq7sA5paGt8vErerK2fomdffcPZ2BtVF4pS4PoBWNF+GZrG6rPA215y9e7h6gt2xv1FRJ3WyfbN4glcw=,iv:H5AQh6SlCixvTeCv9/ALjKvqCZU73h8+nCQthAwXf2k=,tag:bUQnhrhlVH/1Ed8kpVOM0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
