---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: babybuddy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: babybuddy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_ENGINE: "django.db.backends.postgresql"
        DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        DB_NAME: &dbName babybuddy
        SECRET_KEY: "{{ .SECRET_KEY }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: babybuddy
    - extract:
        key: cloudnative-pg
