---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./bazarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./plex/ks.yaml
  - ./plexovic-gatus/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./tautulli/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-4k/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./shelfmark/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-4k/ks.yaml
  - ./unpackerr/ks.yaml
  - ./xteve/ks.yaml
