---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./claim.yaml
  - ./garage.yaml
  - ./r2.yaml
  - ./minio-legacy.yaml # Temporary: restore-only access to old Minio backups
