---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-nas
  namespace: default
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - nas.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: external-nas
          port: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: external-nas
  namespace: default
spec:
  ports:
    - name: external-nas
      port: 5001
  type: ExternalName
  externalName: nas-direct.${SECRET_DOMAIN}
