---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-nas
  namespace: default
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - nas.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: external-nas
          namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: external-nas
  namespace: default
spec:
  appProtocols:
    - gateway.envoyproxy.io/wss
  endpoints:
    - fqdn:
        hostname: nas-direct.${SECRET_DOMAIN}
        port: 5001
  tls:
    insecureSkipVerify: true
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: external-nas
  namespace: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: external-nas
  useClientProtocol: true
