---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-nvr
  namespace: default
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - nvr.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: external-nvr
          namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: external-nvr
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: nvr-direct.${SECRET_DOMAIN}
        port: 5001
  tls:
    insecureSkipVerify: true
