---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
# configMapGenerator:
#   - name: evcc-configmap
#     files:
#       - evcc.yaml=./config/evcc.yaml
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
