---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  activeDeadlineSeconds: 43200
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 568
    fsGroup: 568
    runAsNonRoot: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
  trigger:
    schedule: 0 */12 * * *
  repository:
    repository: volsync-maintenance-secret
