---
apiVersion: v1
kind: ConfigMap
metadata:
  name: molt-config
data:
  openclaw.json: |
    {
      "agent": {
        "model": "anthropic/claude-opus-4-5"
      },
      "gateway": {
        "bind": "0.0.0.0",
        "port": 18789
      },
      "channels": {
        "telegram": {
          "enabled": true
        }
      }
    }
