---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-kiosk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-kiosk-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KIOSK_IMMICH_API_KEY: "{{ .IMMICH_KIOSK_API_KEY }}"
        OPENWEATHERMAP_API_KEY: "{{ .OPENWEATHERMAP_API_KEY }}"
        WEATHER_LAT: "{{ .WEATHER_LAT }}"
        WEATHER_LON: "{{ .WEATHER_LON }}"
        WEATHER_LOCATION_NAME: "{{ .WEATHER_LOCATION_NAME }}"
  dataFrom:
    - extract:
        key: immich-kiosk
