---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-certificates
  namespace: network
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/network/envoy-gateway/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: network
spec:
  dependsOn:
    - name: envoy-gateway-certificates
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/network/envoy-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-proxy
  namespace: network
spec:
  dependsOn:
    - name: envoy-gateway
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/network/envoy-gateway/proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
