---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - X-Forwarded-Proto
      - cookie
    http:
      backendRefs:
        - name: authelia
          namespace: security
          port: 80
      path: /api/verify
      headersToBackend:
        - Remote-User
        - Remote-Name
        - Remote-Groups
        - Remote-Email
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
